import type { NextPage } from 'next';
import Head from 'next/head';
import { toggleTheme } from '../features/themeSlice';
import { useDispatch } from 'react-redux';
import Layout from '../components/Layout';
import { Switch } from 'antd';
import styled from 'styled-components';
import Button from '../components/antdCustomeComponents/Button';

const SwitchButon = styled(Switch)`
  background-color: ${(props) => props.theme.fontColor};
`;

const Home: NextPage = () => {
  const dispatch = useDispatch();

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Discover and Collect your favorite digital Nfts </h1>
      <Button>Explore</Button>
      <SwitchButon defaultChecked onChange={() => dispatch(toggleTheme())} />
    </Layout>
  );
};

export default Home;
